apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus-operator
  name: snd1-prom-prometheus-operat-alert.rules
  namespace: default
spec:
  groups:
    - name: alert.rules
      rules:
        - alert: EndpointDown
          annotations:
            message: '{{ $value }}% of the {{ $labels.job }} targets are down.'
            runbook_url: https://github.com/polarpoint/prometheus-runbooks/blob/master/runbook.md#alert-name-targetdown
            dashboard:  https://dashboard.pohzn.com/
          expr: probe_success == 0
          for: 10s
          labels:
            severity: "critical"
